MinSheng_MIS/Models/EquipmentOperatingManual.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinSheng_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentOperatingManual
    {
        public string EOMSN { get; set; }
        public string EName { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string FilePath { get; set; }
    }
}

MinSheng_MIS/Models/ViewModels/EquipmentOperatingManualViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinSheng_MIS.Models.ViewModels
{
    public class EquipmentOperatingManualViewModel
    {
        public string EOMSN { get; set; }
        public string EName { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public HttpPostedFileBase ManualFile { get; set; }
    }
}

MinSheng_MIS/Controllers/EquipmentOperatingManualController.cs
using MinSheng_MIS.Models;
using MinSheng_MIS.Models.ViewModels;
using MinSheng_MIS.Services;
using MinSheng_MIS.Services.Helpers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MinSheng_MIS.Controllers
{
    public class EquipmentOperatingManualController : Controller
    {
        Bimfm_MinSheng_MISEntities db = new Bimfm_MinSheng_MISEntities();

        #region 操作手冊
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region 新增 設備操作手冊
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(EquipmentOperatingManualViewModel eom)
        {
            try
            {
                JObject jo = new JObject();
                #region 先檢查是否有同設備名稱&廠牌&型號 之操作手冊存在
                var isexist = db.EquipmentOperatingManual.Where(x => x.EName == eom.EName && x.Brand == eom.Brand && x.Model == eom.Model);
                if (isexist.Count() > 0)
                {
                    return Content("此操作手冊已存在!", "application/json");
                }
                #endregion
                #region 存設備操作手冊
                var (isValid, erroeMessage) = ComFunc.IsConformedForImageAndPdf(eom.ManualFile);
                if (!isValid)
                {
                    return Content(erroeMessage, "application/json");
                }
                else
                {
                    string Folder = Server.MapPath("~/Files/EquipmentOperatingManual");
                    System.IO.Directory.CreateDirectory(Folder);
                    var lastEOMSN = db.EquipmentOperatingManual.OrderByDescending(x => x.EOMSN).FirstOrDefault();
                    var num = 1;
                    if (lastEOMSN != null)
                    {
                        num = Convert.ToInt32(lastEOMSN.EOMSN) + 1;
                    }
                    var newEOMSN = num.ToString().PadLeft(6, '0');
                    string Filename = newEOMSN + Path.GetExtension(eom.ManualFile.FileName);
                    string filefullpath = Path.Combine(Folder, Filename);
                    eom.ManualFile.SaveAs(filefullpath);
                    #endregion
                    #region 新增設備操作手冊至資料庫
                    var addeom = new EquipmentOperatingManualService();
                    addeom.AddEquipmentOperatingManual(eom, newEOMSN, Filename);
                    #endregion
                    jo.Add("Succeed", true);
                    string result = JsonConvert.SerializeObject(jo);
                    return Content(result, "application/json");
                }
            }
            catch (Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion

        #region 編輯 設備操作手冊
        public ActionResult Edit(string id)
        {
            ViewBag.id = id;
            return View();
        }
        [HttpGet]
        public ActionResult Readbody(string id)
        {
            try
            {
                JObject jo = new JObject();
                var item = db.EquipmentOperatingManual.Find(id);
                jo["EOMSN"] = item.EOMSN;
                jo["EName"] = item.EName;
                jo["Brand"] = item.Brand;
                jo["Model"] = item.Model;
                jo["ManualFile"] = !string.IsNullOrEmpty(item.FilePath) ? "/Files/EquipmentOperatingManual" + item.FilePath : null;
                jo.Add("Succeed", true);
                string result = JsonConvert.SerializeObject(jo);

                return Content(result, "application/json");
            }
            catch(Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        [HttpPost]
        public ActionResult Edit(EquipmentOperatingManualViewModel eom)
        {
            try
            {
                JObject jo = new JObject();
                #region 先檢查是否有同設備名稱&廠牌&型號 之操作手冊存在
                var isexist = db.EquipmentOperatingManual.Where(x => x.EName == eom.EName && x.Brand == eom.Brand && x.Model == eom.Model && x.EOMSN != eom.EOMSN);
                if (isexist.Count() > 0)
                {
                    return Content("此操作手冊已存在!", "application/json");
                }
                #endregion
                string Filename = "";
                #region 存設備操作手冊
                if (eom.ManualFile != null)
                {
                    var (isValid, erroeMessage) = ComFunc.IsConformedForImageAndPdf(eom.ManualFile);
                    if (!isValid)
                    {
                        return Content(erroeMessage, "application/json");
                    }
                    else
                    {
                        string file = db.EquipmentOperatingManual.Find(eom.EOMSN).FilePath.ToString();
                        string fillfullpath = Server.MapPath($"~/Files/EquipmentOperatingManual{file}");
                        if (System.IO.File.Exists(fillfullpath))
                        {
                            System.IO.File.Delete(fillfullpath);
                        }
                        string Folder = Server.MapPath("~/Files/EquipmentOperatingManual");
                        System.IO.Directory.CreateDirectory(Folder);
                        Filename = eom.EOMSN + Path.GetExtension(eom.ManualFile.FileName);
                        string filefullpath = Path.Combine(Folder, Filename);
                        eom.ManualFile.SaveAs(filefullpath);
                    }
                }

                #endregion
                #region 編輯設備操作手冊至資料庫
                var addeom = new EquipmentOperatingManualService();
                addeom.EditEquipmentOperatingManual(eom, eom.EOMSN, Filename);
                #endregion
                jo.Add("Succeed", true);
                string result = JsonConvert.SerializeObject(jo);
                return Content(result, "application/json");
            }
            catch(Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion

        #region 刪除 設備操作手冊
        public ActionResult Delete(string id)
        {
            ViewBag.id = id;
            return View();
        }
        #endregion

        #region 設備操作手冊資料
        public ActionResult ReadBody(string id)
        {
            try
            {
                JObject jo = new JObject();
                var data = db.EquipmentOperatingManual.Find(id);

                return Content("53", "application/json");
            }
            catch (Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        [HttpPost]
        public ActionResult DeleteEOM(string id)
        {
            try
            {
                JObject jo = new JObject();

                #region 刪除設備操作手冊
                var eom = db.EquipmentOperatingManual.Find(id);
                string fillfullpath = Server.MapPath($"~/Files/EquipmentOperatingManual{eom.FilePath}");
                if (System.IO.File.Exists(fillfullpath))
                {
                    System.IO.File.Delete(fillfullpath);
                }

                #endregion
                #region 刪除設備操作手冊至資料庫
                db.EquipmentOperatingManual.Remove(eom);
                db.SaveChanges();
                #endregion
                jo.Add("Succeed", true);
                string result = JsonConvert.SerializeObject(jo);
                return Content(result, "application/json");
            }
            catch (Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion
    }
}

MinSheng_MIS/Views/EquipmentOperatingManual/Create.cshtml
@{
    ViewBag.Title = "新增設備操作手冊";
}
@section styles {
    @Html.Partial("DataGridScripts")
}

<h2>@ViewBag.Title</h2>

<section>
    <div class="edit-area edit-area-xs flex-lg-row">
        <form class="form">
            <div class="form-group-zone">
                <div class="form-group required">
                    <label for="EName">設備名稱</label>
                    <select class="form-select" name="EName" id="EName" required>
                        <option value="">請選擇</option>
                    </select>
                    <input class="form-control" id="EName" name="EName" type="text" hidden />
                </div>

                <div class="form-group required">
                    <label for="Brand">廠牌</label>
                    <input class="form-control" id="Brand" name="Brand" type="text" maxlength="50" required />
                </div>

                <div class="form-group required">
                    <label for="Model">型號</label>
                    <input class="form-control" id="Model" name="Model" type="text" maxlength="50" required />
                </div>

                <div id="FileUploader"></div>
            </div>
        </form>
    </div>
</section>
    <div class="edit-button-area">
        <button class="btn btn-back" id="back">返回</button>
        <button class="btn btn-export" id="submit">新增</button>
    </div>

    @section scripts {
        <script>
        var fileUploader
        $(async function () {
            addButtonEvent();
            await formDropdown.pushSelect({ id: "EName", url: '@Url.Action("EName", "DropDownList")' });

            fileUploader = new FileUploader({
                container: "#FileUploader",
                className: "form-group required",
                label: "設備操作手冊檔案",
                id: "DesignDiagrams",
                customValidityText: "請上傳設備操作手冊"
            })

        });

        function save() {
            //重置自訂驗證錯誤訊息
            getAllParams().forEach((e) => {
                e.setCustomValidity('');
            })
            //自訂驗證錯誤
            fileUploader.setExtensionValidity(fileUploader.checkAllExtension())
            let isValidity = [...document.forms].map(e => e.reportValidity()).every(e => e);
            console.log("todo save():", isValidity)
            if (!isValidity) return;

            var form = new FormData();
            form.append("EName", document.getElementById("EName").value);
            form.append("Brand", document.getElementById("Brand").value);
            form.append("Model", document.getElementById("Model").value);

            if (fileUploader.hasFile()) {
                form.append("ManualFile", fileUploader.getFile());
            }

            console.log(Object.fromEntries(form.entries()));

            $.ajax({
                url: "/EquipmentOperatingManual/Create",
                data: form,
                type: "POST",
                contentType: false,
                processData: false,
                success: onSuccess,
                error: onError
            })

            function onSuccess(res) {
                console.log(res);
                createDialogModal({
                    id: "DialogModal-Success", inner: "新增成功！",
                    onHide: () => { window.location.href = "/EquipmentOperatingManual/Index"; }
                });
            }
            function onError(res) {
                console.log(res);
                createDialogModal({ id: "DialogModal-Error", inner: `新增失敗！` + `${res?.responseText || ""}` })
            }
        }

        function addButtonEvent() {
            $("#back").click(function () {
                history.back();
            })

            $("#submit").click(function () {
                save();
            })
        }
        </script>
    }

MinSheng_MIS/Views/EquipmentOperatingManual/Delete.cshtml
@{
    ViewBag.Title = "刪除設備操作手冊";
}
@section styles {
    <script src="/Scripts/datatable.js" defer></script>
    <script src="/Scripts/ImageDisplay.js" defer></script>
}

<h2>@ViewBag.Title</h2>

<input type="text" id="EOMSN" name="EOMSN" value="@ViewBag.id" hidden>

<section>
    <div class="info-area">
        <div class="datatable datatable-small">
            <div class="datatable-body">
                <table class="datatable-table"></table>
            </div>
        </div>
    </div>
</section>

<div class="edit-button-area">
    <button class="btn btn-back" id="back">返回</button>
    <button class="btn btn-delete" id="delete">刪除</button>
</div>

@section scripts {
    <script>
        const EOMSN = '@ViewBag.id';
        let apiUrl = '@Url.Action("ReadBody", "EquipmentOperatingManual")' + `/${EOMSN}`;
        //let apiUrl = null;

        const fakeData = {
            EOMSN: "A棟",
            //System: "1F",
            //SubSystem: "BT",
            EName: "BT-11",
            Brand: "M7-126",
            Model: "空調控制配置平面圖",
            ManualFile: "2023/04/11 10:30:26"
        }

        const sn = [
            { text: "設備操作手冊編號", value: "EOMSN" },
            //{ text: "系統別", value: "System" },
            //{ text: "子系統別", value: "SubSystem" },
            { text: "設備名稱", value: "EName" },
            { text: "廠牌", value: "Brand" },
            { text: "型號", value: "Model" },
            {
                text: "設備操作手冊檔案", value: "ManualFile", formatter: (v) => {
                    if (v.split('.').at(-1).toLowerCase() === "pdf") {
                        return `<a href="/Files/EquipmentOperatingManual${v}" target="_blank">${v.split('/').at(-1)}</a>`;
                    }
                    else {
                        return `<div class="datatable-img-area justify-content-center"><div class="datatable-img-item"><img src="${v}"/></div></div>`;
                    }
                }
            },
        ]

        $(async function () {
            addButtonEvent();
            readData(apiUrl);
        });

        function readData(url = null) {

            url == null ? onSuccess(fakeData) :
                $.ajax({
                    url: url,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: onSuccess,
                    error: onError
                })

            async function onSuccess(res) {
                console.log(res);

                $(".datatable-table").append(createTableInner(res, sn))
                ImageDisplay(".datatable-img-item>img");
            }
            function onError(res) {
                console.log(res);
            }
        }

        function addButtonEvent() {
            $("#back").click(function () {
                history.back();
            })

            $("#delete").click(function () {
                createDeleteDialog({
                    url: '@Url.Action("DeleteEOM", "EquipmentOperatingManual")/' + EOMSN,
                    data: EOMSN,
                    onSuccess() {
                        let url = '@Url.Action("Index", "EquipmentOperatingManual")';
                        window.location.href = url;
                    }
                })
            });
        }
    </script>
}

MinSheng_MIS/Views/EquipmentOperatingManual/Edit.cshtml
@{
    ViewBag.Title = "編輯設備操作手冊";
}
@section styles {
    @Html.Partial("DataGridScripts")

    <style>
        @@media(min - width: 992px) {
                .edit-area .form {
                    grid-template-columns: 250px 250px;
                }
            }
        </style>
    }

    <h2>@ViewBag.Title</h2>

    <section>
        <div class="edit-area edit-area-xs flex-lg-row">
            <form class="form">
                <div class="form-group-zone">
                    <div class="form-group required" hidden>
                        <label for="EOMSN">設備操作手冊編號</label>
                        <input class="form-control" id="EOMSN" name="EOMSN" type="text" maxlength="50" required />
                    </div>

                    <div class="form-group required">
                        <label for="EName">設備名稱</label>
                        <select class="form-select" name="EName" id="EName" required>
                            <option value="">請選擇</option>
                        </select>
                        <input class="form-control" id="EName" name="EName" type="text" hidden />
                    </div>

                    <div class="form-group required">
                        <label for="Brand">廠牌</label>
                        <input class="form-control" id="Brand" name="Brand" type="text" maxlength="50" required />
                    </div>

                    <div class="form-group required">
                        <label for="Model">型號</label>
                        <input class="form-control" id="Model" name="Model" type="text" maxlength="50" required />
                    </div>

                    <div id="FileUploader"></div>
                </div>
            </form>
        </div>
    </section>
    <div class="edit-button-area">
        <button class="btn btn-back" id="back">返回</button>
        <button class="btn btn-export" id="submit">儲存</button>
    </div>

    @section scripts {
        <script>

            const EOMSN = '@ViewBag.id';
            let apiUrl = '@Url.Action("ReadBody", "EquipmentOperatingManual")' + `/${EOMSN}`;
            //let apiUrl = null;

            const fakeData = {
                EName: "除霧皮帶輸送機",
                Brand: "A廠牌",
                Model: "HT-6356",
                ManualFile: "2023-03-30_B.png",
            }

            var fileUploader
            $(async function () {
                $("#_checkFilePath").prop("checked", true);
                addButtonEvent();

                fileUploader = new FileUploader({
                    container: "#FileUploader",
                    className: "form-group required",
                    label: "設備操作手冊檔案",
                    id: "DesignDiagrams",
                    customValidityText: "請上傳設備操作手冊"
                })

                readData(apiUrl);
            });

            function readData(url = null) {

                url == null ? onSuccess(fakeData) :
                    $.ajax({
                        url: url,
                        type: "GET",
                        dataType: "json",
                        contentType: "application/json;charset=utf-8",
                        success: onSuccess,
                        error: onError
                    })

                async function onSuccess(res) {
                    console.log(res);
                    await formDropdown.pushSelect({ id: "EName", url: '@Url.Action("EName", "DropDownList")' });

                    for (const [k, v] of Object.entries(res)) {
                        switch (k) {
                            case "ManualFile":
                                fileUploader.setFile(res.ManualFile);
                                break;
                            default:
                                $(`#${k}`).val(v);
                                break;
                        }
                    }
                }
                function onError(res) {
                    console.log(res);
                }
            }

            function save() {
                //重置自訂驗證錯誤訊息
                getAllParams().forEach((e) => {
                    e.setCustomValidity('');
                })
                //自訂驗證錯誤
                fileUploader.setExtensionValidity(fileUploader.checkAllExtension())
                let isValidity = [...document.forms].map(e => e.reportValidity()).every(e => e);
                console.log("todo save():", isValidity)
                if (!isValidity) return;

                var form = new FormData();
                form.append("EOMSN", document.getElementById("EOMSN").value);
                form.append("EName", document.getElementById("EName").value);
                form.append("Brand", document.getElementById("Brand").value);
                form.append("Model", document.getElementById("Model").value);
                if (fileUploader.hasFile()) {
                    form.append("ManualFile", fileUploader.getFile());
                }

                console.log(Object.fromEntries(form.entries()));

                $.ajax({
                    url: "/EquipmentOperatingManual/Edit",
                    data: form,
                    type: "POST",
                    contentType: false,
                    processData: false,
                    success: onSuccess,
                    error: onError
                })

                function onSuccess(res) {
                    console.log(res);
                    createDialogModal({
                        id: "DialogModal-Success", inner: "儲存成功！",
                        onHide: () => { window.location.href = "/EquipmentOperatingManual/Index"; }
                    });
                }
                function onError(res) {
                    console.log(res);
                    createDialogModal({ id: "DialogModal-Error", inner: `儲存失敗！` + `${res?.responseText || ""}` })
                }
            }

            function addButtonEvent() {
                $("#back").click(function () {
                    history.back();
                })

                $("#submit").click(function () {
                    save();
                })
            }
        </script>
    }

MinSheng_MIS/Views/EquipmentOperatingManual/Index.cshtml
@{
    ViewBag.Title = "設備操作手冊";
}

@section styles {
    @Html.Partial("DataGridScripts")
}

<h2>@ViewBag.Title</h2>

<button class="btn btn-create" id="create">新增</button>
<div class="search-area">
    <form class="form" method="post" action="">
        <div class="form-group">
            <label for="EName">設備名稱</label>
            <input class="form-control" id="EName" name="EName" type="text" />
        </div>
        <div class="form-group">
            <label for="Brand">廠牌</label>
            <input class="form-control" id="Brand" name="Brand" type="text" />
        </div>
        <div class="form-group">
            <label for="Model">型號</label>
            <input class="form-control" id="Model" name="Model" type="text" />
        </div>
        <div class="button-group">
            <button type="button" class="btn btn-search" id="search">查詢</button>
            <button type="reset" class="btn btn-clear" id="clear">清除</button>
        </div>
    </form>
</div>

<div class="datagrid-area">
    <table id="DataGrid"></table>
</div>

@section scripts {
    <script>
        var getGridJSON = '@Url.Action("EquipmentOperatingManual", "Datagrid")';
        var DataGrid;


        const fakedata = [
            {
                EOMSN: "230502002",
                Filepath: "/EquipmentOperatingManual/230502002.pdf",
                EName: "除霧皮帶輸送機",
                Brand: "A廠牌",
                Model: "HT-6356",
            },
            {
                EOMSN: "230502002",
                Filepath: "/EquipmentOperatingManual/230502002.pdf",
                EName: "除霧皮帶輸送機",
                Brand: "A廠牌",
                Model: "HT-6356",
            }
        ]
        $(async function () {
            if (!isAuth("1", "2")) {
                document.getElementById('create').remove();
            }

            Initialize_DataGrid(getGridJSON);
            addSearchAreaClickEvent();
        });

        function Initialize_DataGrid(getGridJSON) {
            let dg = new DG();
            DataGrid = dg.init("#DataGrid", {
                url: getGridJSON,
                // data: fakeData,
                method: 'POST',
                queryParams: getQueryParams(),
                idField: 'EOMSN',
                //sortName: 'EOMSN',
                remoteSort: true,
                frozenColumns: [[
                    dg.frozenColumn('_view', (v, row, i) => dg.eventButton(i, "檢視", "view")),
                    isAuth("1", "2") && dg.frozenColumn('_edit', (v, row, i) => dg.eventButton(i, "編輯", "edit")),
                    isAuth("1") && dg.frozenColumn('_delete', (v, row, i) => dg.eventButton(i, "刪除", "delete", { className: "btn btn-datagrid btn-delete" }))
                ]],
                columns: [[
                    dg.hiddenColumn('EOMSN'),
                    dg.hiddenColumn('FilePath'),
                    //dg.column('System', '系統別', 180),
                    //dg.column('SubSystem', '子系統別', 180),
                    dg.column('EName', '設備名稱', 400),
                    dg.column('Brand', '廠牌', 400),
                    dg.column('Model', '型號', 410)
                ]]
            })
            dg.addEvent("view", function (row, i) {
                window.open(`${row.FilePath}`, "_blank")
            })
            dg.addEvent("edit", function (row, i) {
                window.open(`${baseUrl}/Edit/${row.EOMSN}`, "_self")
            })
            dg.addEvent("delete", function (row, i) {
                window.open(`${baseUrl}/Delete/${row.EOMSN}`, "_self")
            })
        }

        //search area onClick Function
        function addSearchAreaClickEvent() {

            $("#search").click(function () {
                DataGrid.datagrid('load', getQueryParams());
            });

            $("#create").click(function () {
                window.open(`${baseUrl}/Create`, "_self");
            });
        }
    </script>
}