MinSheng_MIS/Models/ViewModels/LaboratoryMaintenance_ManagementViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MinSheng_MIS.Models.ViewModels
{
    public class LM_Info
    {
        [Required]
        [StringLength(200, ErrorMessage = "{0} 的長度至少必須為{2}個字元，且最多{1}個字元。", MinimumLength = 1)]
        [Display(Name = "維護類型")]
        public string MType { get; set; } //維護類型
        [Required]
        [StringLength(200, ErrorMessage = "{0} 的長度至少必須為{2}個字元，且最多{1}個字元。", MinimumLength = 1)]
        [Display(Name = "標題")]
        public string MTitle { get; set; } //標題
        [StringLength(200, ErrorMessage = "{0} 的長度最多{1}個字元。")]
        [Display(Name = "說明")]
        public string MContent { get; set; } //說明
        public HttpPostedFileBase MFile { get; set; } //新增的維護檔案
        //--------------------------------------------
        [Required]
        public string LMSN { get; set; } //實驗室維護單號
        public string MFileName { get; set; } //已刪除的維護檔案
    }

    public class LM_ViewModel
    {
        public string LMSN { get; set; } //實驗室維護單號
        public string MType { get; set; } //維護類型
        public string MTitle { get; set; } //標題
        public string MContent { get; set; } //說明
        public string UploadUserName { get; set; } //上傳者
        public string UploadDateTime { get; set; } //上傳日期時間
        public string FilePath { get; set; } //維護檔案
    }
}

MinSheng_MIS/Controllers/LaboratoryMaintenance_ManagementController.cs
using MinSheng_MIS.Models;
using MinSheng_MIS.Models.ViewModels;
using MinSheng_MIS.Services;
using MinSheng_MIS.Services.Helpers;
using Newtonsoft.Json;
using System;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MinSheng_MIS.Controllers
{
	public class LaboratoryMaintenance_ManagementController : Controller
	{
        Bimfm_MinSheng_MISEntities db = new Bimfm_MinSheng_MISEntities();
        static readonly string folderPath = "Files/LaboratoryMaintenance";
        // GET: LaboratoryMaintenance_Management
        #region 實驗室維護管理
        public ActionResult Index()
		{
			return View();
		}
		#endregion

		#region 新增實驗室維護管理
		public ActionResult Create()
		{
			return View();
		}

        [HttpPost]
        public async Task<ActionResult> CreateLaboratoryMaintenance(LM_Info lm_info)
		{
            try
            {
                ModelState.Remove("LMSN");
                if (!ModelState.IsValid) return Helper.HandleInvalidModelState(this);  // Data Annotation未通過

                #region 檢查是否有同維護類型&同標題的實驗室維護
                var isExist = db.LaboratoryMaintenance.Count(x => x.MType == lm_info.MType && x.MTitle == lm_info.MTitle);
                if (isExist > 0)
                {
                    return Content("此實驗室維護已存在", "application/json; charset=utf-8");
                }
                #endregion

                DateTime now = DateTime.Now;
                // 新增實驗室維護
                var count = await db.LaboratoryMaintenance.Where(x => x.UploadDateTime.HasValue && DbFunctions.TruncateTime(x.UploadDateTime.Value) == now.Date).CountAsync() + 1;  // 實驗室維護流水碼
                var maintenance = new LaboratoryMaintenance
                {
                    LMSN = now.ToString("yyMMdd") + count.ToString().PadLeft(3, '0'),
                    MType = lm_info.MType,
                    MTitle = lm_info.MTitle,
                    MContent = lm_info.MContent,
                    UploadUserName = User.Identity.Name,
                    UploadDateTime = now
                };
                // [維護檔案]檔案處理，目前只提供單個檔案上傳
                if (lm_info.MFile != null && lm_info.MFile.ContentLength > 0) // 上傳
                {
                    var File = lm_info.MFile;
                    string extension = Path.GetExtension(File.FileName); // 檔案副檔名
                    if (ComFunc.IsConformedForDocument(File.ContentType, extension)
                        || ComFunc.IsConformedForPdf(File.ContentType, extension)
                        || ComFunc.IsConformedForImage(File.ContentType, extension)) // 檔案白名單檢查
                    {
                        if (File.ContentLength > 10 * 1024 * 1024)
                        {
                            return Content("<br>檔案大小不得超過 10MB。", "application/json; charset=utf-8");
                        }
                        // 檔案上傳
                        if (!ComFunc.UploadFile(File, Server.MapPath($"~/{folderPath}/"), maintenance.LMSN))
                            return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "檔案上傳過程出錯！");
                        maintenance.MFile = maintenance.LMSN + extension;
                    }
                    else
                        //return new HttpStatusCodeResult(HttpStatusCode.UnsupportedMediaType, "非系統可接受的檔案格式！");
                        return Content("<br>非系統可接受的檔案格式!<br>僅支援上傳圖片、Word或PDF！", "application/json; charset=utf-8");
                }
                db.LaboratoryMaintenance.Add(maintenance);
                await db.SaveChangesAsync();

                return Content("Succeed");
            }
            catch(Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion

        #region 編輯實驗室維護管理
        public ActionResult Edit(string id)
		{
            ViewBag.id = id;
            return View();
		}

        [HttpPost]
        public async Task<ActionResult> EditLaboratoryMaintenance(LM_Info lm_info)
        {
            try
            {
                if (!ModelState.IsValid) return Helper.HandleInvalidModelState(this);  // Data Annotation未通過

                var maintenance = await db.LaboratoryMaintenance.FirstOrDefaultAsync(x => x.LMSN == lm_info.LMSN);
                if (maintenance == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "LMSN is Undefined.");

                #region 檢查是否有同維護類型&同標題的實驗室維護
                var isExist = db.LaboratoryMaintenance.Count(x => x.MType == lm_info.MType && x.MTitle == lm_info.MTitle && x.LMSN != lm_info.LMSN);
                if (isExist > 0)
                {
                    return Content("此實驗室維護已存在", "application/json; charset=utf-8");
                }
                #endregion

                // 編輯實驗室維護資訊
                maintenance.MType = lm_info.MType;
                maintenance.MTitle = lm_info.MTitle;
                maintenance.MContent = lm_info.MContent;
                // [維護檔案]檔案處理，目前只提供單個檔案上傳及刪除
                if (lm_info.MFileName == null && !string.IsNullOrEmpty(maintenance.MFile)) // 當使用者介面目前無檔案(不包含本次上傳的檔案)時，若此實驗室維護具有維護檔案，應刪除。
                {
                    ComFunc.DeleteFile(Server.MapPath($"~/{folderPath}/"), maintenance.MFile, null);
                    maintenance.MFile = null;
                }
                if (lm_info.MFile != null && lm_info.MFile.ContentLength > 0) // 上傳
                {
                    var newFile = lm_info.MFile;
                    string extension = Path.GetExtension(newFile.FileName); // 檔案副檔名
                    if (ComFunc.IsConformedForDocument(newFile.ContentType, extension)
                        || ComFunc.IsConformedForPdf(newFile.ContentType, extension)
                        || ComFunc.IsConformedForImage(newFile.ContentType, extension)) // 檔案白名單檢查
                    {
                        if (newFile.ContentLength > 10 * 1024 * 1024)
                        {
                            return Content("<br>檔案大小不得超過 10MB。", "application/json; charset=utf-8");
                        }
                        // 檔案上傳
                        if (!ComFunc.UploadFile(newFile, Server.MapPath($"~/{folderPath}/"), maintenance.LMSN))
                            return new HttpStatusCodeResult(HttpStatusCode.InternalServerError, "檔案上傳過程出錯！");
                        maintenance.MFile = maintenance.LMSN + extension;
                    }
                    else
                        //return new HttpStatusCodeResult(HttpStatusCode.UnsupportedMediaType, "非系統可接受的檔案格式！");
                        return Content("<br>非系統可接受的檔案格式!<br>僅支援上傳圖片、Word或PDF！", "application/json; charset=utf-8");
                }

                db.LaboratoryMaintenance.AddOrUpdate(maintenance);
                await db.SaveChangesAsync();

                return Json(new { Message = "Succeed" });
            }
            catch(Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion

        #region 實驗室維護管理詳情
        public ActionResult Detail(string id)
		{
            ViewBag.id = id;
            return View();
		}

        public async Task<ActionResult> Read_Data(string id)
        {
            try
            {
                var maintenance = await db.LaboratoryMaintenance.FirstOrDefaultAsync(x => x.LMSN == id);
                if (maintenance == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "LMSN is Undefined.");

                LM_ViewModel model = new LM_ViewModel
                {
                    LMSN = maintenance.LMSN,
                    MType = maintenance.MType,
                    MTitle = maintenance.MTitle,
                    MContent = maintenance.MContent,
                    UploadUserName = db.AspNetUsers.FirstOrDefaultAsync(x => x.UserName == maintenance.UploadUserName)?.Result.MyName,
                    UploadDateTime = maintenance.UploadDateTime?.ToString("yyyy-MM-dd HH:mm:ss"),
                    FilePath = !string.IsNullOrEmpty(maintenance.MFile) ? ComFunc.UrlMaker(folderPath, maintenance.MFile) : null
                };
                return Content(JsonConvert.SerializeObject(model), "application/json");
            }
            catch(Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion
    }
}

MinSheng_MIS/Views/LaboratoryMaintenance_Management/Create.cshtml
@{
    ViewBag.Title = "新增實驗室維護管理";
}
@section styles {
    <script src="/Scripts/datatable.js" defer></script>
    <script src="/Scripts/tool.js" defer></script>
    <style>
        @@media (min-width: 992px) {
            .edit-area .form {
                grid-template-columns: 250px 250px;
            }
        }
    </style>
}

<h2>@ViewBag.Title</h2>

<section>
    <div class="edit-area edit-area-sm flex-lg-row">
        <form class="form">
            <div class="form-group-zone">
                <div class="form-group required">
                    <label for="MType">維護類型</label>
                    <input class="form-control" id="MType" name="MType" type="text" required>
                </div>

                <div class="form-group required">
                    <label for="MTitle">標題</label>
                    <input class="form-control" id="MTitle" name="MTitle" type="text" required>
                </div>

                <div class="form-group" style="grid-column: auto/span 2;">
                    <label for="MContent">說明</label>
                    <textarea class="form-control" name="MContent" id="MContent" rows="1"></textarea>
                </div>
                <div id="FileUploader"></div>
            </div>
        </form>
    </div>
</section>

    <div class="edit-button-area">
        <button class="btn btn-back" id="back">返回</button>
        <button class="btn btn-export" id="submit">新增</button>
    </div>

    @section scripts {
        <script>
        var fileUploader
        $(async function () {
            addButtonEvent();
            fileUploader = new FileUploader({
                container: "#FileUploader",
                className: "form-group g-col-2 required",
                label: "維護檔案",
                id: "File"
            })
        });

        function save() {
            //重置自訂驗證錯誤訊息
            getAllParams().forEach((e) => {
                e.setCustomValidity('');
            })
            //自訂驗證錯誤
            fileUploader.setExtensionValidity(fileUploader.checkAllExtension())
            let isValidity = [...document.forms].map(e => e.reportValidity()).every(e => e);
            console.log("isValidity():", isValidity)
            if (!isValidity) return;

            var form = new FormData();
            form.append("MType", document.getElementById("MType").value);
            form.append("MTitle", document.getElementById("MTitle").value);
            form.append("MContent", document.getElementById("MContent").value);
            if (fileUploader.hasFile()) {
                form.append("MFile", fileUploader.getFile());
            }
            console.log(Object.fromEntries(form.entries()));
            $.ajax({
                url: '@Url.Action("CreateLaboratoryMaintenance", "LaboratoryMaintenance_Management")',
                data: form,
                type: "POST",
                contentType: false,
                processData: false,
                success: onSuccess,
                error: onError
            })
            function onSuccess(res) {
                console.log(res);
                createDialogModal({
                    id: "DialogModal-Success", inner: "新增成功！",
                    onHide: () => { window.location.href = "/LaboratoryMaintenance_Management/Index"; }
                });
            }
            function onError(res) {
                console.log(res);
                createDialogModal({ id: "DialogModal-Error", inner: `新增失敗！` + `${res?.responseText || ""}` })
            }
        }

        function addButtonEvent() {
            $("#back").click(function () {
                history.back();
            })

            $("#submit").click(function () {
                save();
            })
        }
        </script>
    }

MinSheng_MIS/Views/LaboratoryMaintenance_Management/Detail.cshtml
@{
    ViewBag.Title = "實驗室維護管理詳情";
}
@section styles {
    <script src="/Scripts/datatable.js" defer></script>
}

<h2>@ViewBag.Title</h2>

<section>
    <div class="info-area">
        <div class="datatable datatable-small">
            <div class="datatable-body">
                <table class="datatable-table"></table>
            </div>
        </div>
    </div>
</section>

        @section scripts {
            <script>
        const LMSN = '@ViewBag.id';
        let apiUrl = '@Url.Action("Read_Data", "LaboratoryMaintenance_Management")' + `/${LMSN}`;
        //let apiUrl = null;

        const fakeData = {
            LMSN: "1",
            MType: "人員維護",
            MTitle: "水質分析室緊急逃生路線",
            MContent: "緊急逃生說明",
            UploadUserName: "王大明",
            UploadDateTime: "2023/11/11 12:01:01",
            FilePath: "/Files/a.pdf"
        }

        const sn = [
            { text: "維護類型", value: "MType" },
            { text: "標題", value: "MTitle" },
            { text: "說明", value: "MContent" },
            { text: "上傳者", value: "UploadUserName" },
            { text: "上傳日期時間", value: "UploadDateTime", type: "Date" },
            { text: "維護檔案", value: "FilePath", url: true },
        ]


        $(function () {
            addButtonEvent();
            readData(apiUrl);
        })

        function readData(url = null) {

            url == null ? onSuccess(fakeData) :
                $.ajax({
                    url: url,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: onSuccess,
                    error: onError
                })

            async function onSuccess(res) {
                console.log(res);
                $(".datatable-table").append(createTableInner(res, sn))
            }
            function onError(res) {
                console.log(res);
            }
        }

        function addButtonEvent() {
            $("#back").click(function () {
                history.back();
            })
        }
            </script>
        }

MinSheng_MIS/Views/LaboratoryMaintenance_Management/Edit.cshtml
@{
    ViewBag.Title = "編輯實驗室維護管理";
}
@section styles {
    <script src="/Scripts/datatable.js" defer></script>
    <script src="/Scripts/tool.js" defer></script>
    <style>
        @@media (min-width: 992px) {
            .edit-area .form {
                grid-template-columns: 250px 250px;
            }
        }
    </style>
}

<h2>@ViewBag.Title</h2>

<section>
    <div class="edit-area edit-area-sm flex-lg-row">
        <form class="form">
            <div class="form-group-zone">
                <input type="text" id="LMSN" name="LMSN" hidden>
                <div class="form-group required">
                    <label for="MType">維護類型</label>
                    <input class="form-control" id="MType" name="MType" type="text" required>
                </div>

                <div class="form-group required">
                    <label for="MTitle">標題</label>
                    <input class="form-control" id="MTitle" name="MTitle" type="text" required>
                </div>

                <div class="form-group" style="grid-column: auto/span 2;">
                    <label for="MContent">說明</label>
                    <textarea class="form-control" name="MContent" id="MContent" rows="1"></textarea>
                </div>
                <div id="FileUploader"></div>
            </div>
        </form>
    </div>
</section>
<div class="edit-button-area">
    <button class="btn btn-back" id="back">返回</button>
    <button class="btn btn-export" id="submit">儲存</button>
</div>

@section scripts {
    <script>
        const LMSN = '@ViewBag.id';
        const apiUrl = '@Url.Action("Read_Data", "LaboratoryMaintenance_Management")' + `/${LMSN}`;
        //const apiUrl = null;
        const fakeData = {
            LMSN: "1",
            MType: "人員維護",
            MTitle: "水質分析室緊急逃生路線",
            MContent: "緊急逃生說明",
            FilePath: "/Files/a.pdf"
        }
        var fileUploader
        $(async function () {
            addButtonEvent();
            fileUploader = new FileUploader({
                container: "#FileUploader",
                className: "form-group g-col-2 required",
                label: "維護檔案",
                id: "File",
                customValidity: true
            })
            readData(apiUrl);
        });

        function readData(url = null) {

            url == null ? onSuccess(fakeData) :   //fakeData
                $.ajax({
                    url: url,
                    //data: JSON.stringify(jsonData),
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: onSuccess,
                    error: onError
                })

            function onSuccess(res) {
                console.log(res);
                for (const [k, v] of Object.entries(res)) {
                    $("#" + k).val(v);
                }
                fileUploader.setFile(res.FilePath)
            }
            function onError(res) {
                console.log(res);
            }
        }

        function save() {
            //重置自訂驗證錯誤訊息
            getAllParams().forEach((e) => {
                e.setCustomValidity('');
            })
            //自訂驗證錯誤
            fileUploader.setExtensionValidity(fileUploader.checkAllExtension())
            let isValidity = [...document.forms].map(e => e.reportValidity()).every(e => e);
            console.log("isValidity():", isValidity)
            if (!isValidity) return;

            var form = new FormData();
            form.append("LMSN", document.getElementById("LMSN").value);
            form.append("MType", document.getElementById("MType").value);
            form.append("MTitle", document.getElementById("MTitle").value);
            form.append("MContent", document.getElementById("MContent").value);
            if (fileUploader.hasFile()) {
                let file = fileUploader.getFile()
                if (file?.size) {
                    form.append("MFile", file);
                }
                else {
                    form.append("MFileName", file.name);
                }
            }
            console.log(Object.fromEntries(form.entries()));
            $.ajax({
                url: '@Url.Action("EditLaboratoryMaintenance", "LaboratoryMaintenance_Management")',
                data: form,
                type: "POST",
                contentType: false,
                processData: false,
                success: onSuccess,
                error: onError
            })
            function onSuccess(res) {
                console.log(res);
                createDialogModal({
                    id: "DialogModal-Success", inner: "儲存成功！",
                    onHide: () => { window.location.href = "/LaboratoryMaintenance_Management/Index"; }
                });
            }
            function onError(res) {
                console.log(res);
                createDialogModal({ id: "DialogModal-Error", inner: `儲存失敗！` + `${res?.responseText || ""}` })
            }
        }

        function addButtonEvent() {
            $("#back").click(function () {
                history.back();
            })

            $("#submit").click(function () {
                save();
            })
        }
    </script>
}

MinSheng_MIS/Views/LaboratoryMaintenance_Management/Index.cshtml
@{
    ViewBag.Title = "實驗室維護管理";
}

@section styles {
    @Html.Partial("DataGridScripts")
}

<h2>@ViewBag.Title</h2>

<div class="dg-tool-bar">
    <button class="btn btn-create" id="create">新增</button>
    <div class="search-area">
        <form class="form" method="post" action="">

            <div class="form-group">
                <label for="MType">維護類型</label>
                <select class="form-select" name="MType" id="MType">
                    <option value="">請選擇</option>
                </select>
            </div>

            <div class="form-group">
                <label for="MTitle">標題</label>
                <input class="form-control" id="MTitle" name="MTitle" type="text" />
            </div>

            <div class="form-group">
                <label for="MContent">說明</label>
                <input class="form-control" id="MContent" name="MContent" type="text" />
            </div>

            <div class="button-group">
                <button type="button" class="btn btn-search" id="search">查詢</button>
                <button type="reset" class="btn btn-clear" id="clear">清除</button>
            </div>

        </form>
    </div>

    <div class="datagrid-area">
        <table id="DataGrid"></table>
    </div>
</div>

@section scripts {
    <script>

        var getGridJSON = '@Url.Action("LaboratoryMaintenance_Management", "Datagrid")';
        var DataGrid;

        const fakeData = [
            {
                LMSN: "1",
                MType: "人員維護",
                MTitle: "水質分析室緊急逃生路線",
                MContent: "緊急逃生說明",
                UploadUserName: "王大明",
                UploadDateTime: "2023/11/11 12:01:01"
            }
        ]
        $(async function () {
            if (!isAuth("1", "2")) {
                document.getElementById('create').remove();
            }

            await formDropdown.pushSelect({ id: "MType", url: '@Url.Action("FormMType", "DropDownList")' });
            Initialize_DataGrid(getGridJSON);
            addSearchAreaClickEvent();
        });

        function Initialize_DataGrid(getGridJSON) {
            let dg = new DG();
            DataGrid = dg.init("#DataGrid", {
                url: getGridJSON,
                //data: fakeData,
                method: 'POST',
                queryParams: getQueryParams(),
                idField: 'LMSN',
                //sortName: 'LMSN',
                remoteSort: true,
                frozenColumns: [[
                    dg.frozenColumn('_detail', (v, row, i) => dg.eventButton(i, "詳情", "detail")),
                    isAuth("1", "2") && dg.frozenColumn('_edit', (v, row, i) => dg.eventButton(i, "編輯", "edit")),
                ]],
                columns: [[
                    dg.hiddenColumn('LMSN'),
                    dg.column('MType', '維護類型', 200),
                    dg.column('MTitle', '標題', 400),
                    dg.column('MContent', '說明', 500),
                    dg.column('UploadUserName', '上傳者', 150),
                    dg.column('UploadDateTime', '上傳日期時間', 200, (v, row, i) => {
                        return dateTransform(v);
                    }),
                ]]
            })
            dg.addEvent("detail", function (row, i) {
                window.open(`${baseUrl}/Detail/${row.LMSN}`, "_blank")
            })
            dg.addEvent("edit", function (row, i) {
                window.open(`${baseUrl}/Edit/${row.LMSN}`, "_self")
            })

        }

        //search area onClick Function
        function addSearchAreaClickEvent() {


            $("#search").click(function () {
                DataGrid.datagrid('load', getQueryParams());
            });

            $("#create").click(function () {
                window.open(`${baseUrl}/Create`, "_self");
            });
        }
    </script>
}

MinSheng_MIS/Views/LaboratoryMaintenance_Management/Management.cshtml
@{
    ViewBag.Title = "實驗室維護管理";
}

@section styles {
    @Html.Partial("DataGridScripts")

    <script src="/Scripts/datagrid-management.js" defer></script>
    <script src="/Scripts/tool.js" defer></script>
}

<h2>@ViewBag.Title</h2>

<button class="btn btn-create" id="create">新增</button>
<div class="search-area">
    <form class="form" method="post" action="">

        <div class="form-group">
            <label for="MType">維護類型</label>
            <select class="form-select" name="MType" id="MType">
                <option value="">請選擇</option>
            </select>
        </div>

        <div class="form-group">
            <label for="MTitle">標題</label>
            <input class="form-control" id="MTitle" name="MTitle" type="text" />
        </div>

        <div class="form-group">
            <label for="MContent">說明</label>
            <input class="form-control" id="MContent" name="MContent" type="text" />
        </div>

        <div class="button-group">
            <button type="button" class="btn btn-search" id="search">查詢</button>
            <button type="button" class="btn btn-clear" id="clear">清除</button>
        </div>

    </form>
</div>

<div class="datagrid-area">
    <table id="DataGrid"></table>
</div>

@section scripts {
    <script>

        var getGridJSON = '@Url.Action("LaboratoryMaintenance_Management", "Datagrid")';
        var DataGrid;

        const fakeData = [
            {
                LMSN: "1",
                MType: "人員維護",
                MTitle: "水質分析室緊急逃生路線",
                MContent: "緊急逃生說明",
                UploadUserName: "王大明",
                UploadDateTime: "2023/11/11 12:01:01"
            }
        ]

        $(async function () {
            Initialize_DataGrid(getGridJSON);
            addSearchAreaClickEvent();
            await pushSelect("MType", '@Url.Action("FormMType", "DropDownList")');
        });

        function Initialize_DataGrid(getGridJSON) {
            let dg = new DG();
            DataGrid = dg.init("#DataGrid", {
                url: getGridJSON,
                //data: fakeData,
                method: 'POST',
                queryParams: getQueryParams(),
                idField: 'LMSN',
                //sortName: 'LMSN',
                remoteSort: true,
                frozenColumns: [[
                    dg.frozenColumn('_detail', (v, row, i) => dg.eventButton(i, "詳情", "detail")),
                    dg.frozenColumn('_edit', (v, row, i) => dg.eventButton(i, "編輯", "edit")),
                ]],
                columns: [[
                    dg.hiddenColumn('LMSN'),
                    dg.column('MType', '維護類型', 200),
                    dg.column('MTitle', '標題', 400),
                    dg.column('MContent', '說明', 200),
                    dg.column('UploadUserName', '上傳者', 120),
                    dg.column('UploadDateTime', '上傳日期時間', 200),
                ]]
            })
            dg.addEvent("detail", function (row, i) {
                window.open(`${baseUrl}/Read/${row.LMSN}`, "_blank")
            })
            dg.addEvent("edit", function (row, i) {
                window.open(`${baseUrl}/Edit/${row.LMSN}`, "_self")
            })

        }

        //search area onClick Function
        function addSearchAreaClickEvent() {
            $("#clear").click(function () {
                $(".search-area form")[0].reset();
            });

            $("#search").click(function () {
                DataGrid.datagrid('load', getQueryParams());
            });

            $("#create").click(function () {
                window.open(`${baseUrl}/Create`, "_self");
            });
        }
    </script>
}

MinSheng_MIS/Views/LaboratoryMaintenance_Management/Read.cshtml
@{
    ViewBag.Title = "實驗室維護管理詳情";
}
@section styles {
    <script src="/Scripts/datatable.js" defer></script>
}

<h2>@ViewBag.Title</h2>

<section>
    <div class="info-area">
        <div class="datatable datatable-small">
            <div class="datatable-body">
                <table class="datatable-table"></table>
            </div>
        </div>
    </div>
</section>

        @section scripts {
            <script>
        const LMSN = '@ViewBag.id';
        let apiUrl = '@Url.Action("Read_Data", "LaboratoryMaintenance_Management")' + `/${LMSN}`;
        //let apiUrl = null;

        const fakeData = {
            LMSN: "1",
            MType: "人員維護",
            MTitle: "水質分析室緊急逃生路線",
            MContent: "緊急逃生說明",
            UploadUserName: "王大明",
            UploadDateTime: "2023/11/11 12:01:01",
            FilePath: "/Files/a.pdf"
        }

        const sn = [
            { text: "維護類型", value: "MType" },
            { text: "標題", value: "MTitle" },
            { text: "說明", value: "MContent" },
            { text: "上傳者", value: "UploadUserName" },
            { text: "上傳日期時間", value: "UploadDateTime" },
            { text: "維護檔案", value: "FilePath" },
        ]


        $(function () {
            addButtonEvent();
            readData(apiUrl);
        })

        function readData(url = null) {

            url == null ? onSuccess(fakeData) :
                $.ajax({
                    url: url,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: onSuccess,
                    error: onError
                })

            async function onSuccess(res) {
                console.log(res);
                $(".datatable-table").append(createTableInner(res, sn))
            }
            function onError(res) {
                console.log(res);
            }
        }

        function addButtonEvent() {
            $("#back").click(function () {
                history.back();
            })
        }
            </script>
        }