MinSheng_MIS/Models/ViewModels/WarningMessage_ManagementViewModel.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using static MinSheng_MIS.Services.UniParams;

namespace MinSheng_MIS.Models.ViewModels
{
    public class WarningMessageViewModel
    {
        public string WMSN { get; set; } //警示訊息編號
        public string WMType { get; set; } //事件等級
        public string WMState { get; set; } //事件處理狀況
        public string TimeOfOccurrence { get; set; } //發生時間
        public string Location { get; set; } //發生地點
        public string Message { get; set; } //事件內容
        public List<WarningMessageFillinRecordViewModel> WarningMessageFillinRecord { get; set; } //填報紀錄
    }
    public class WarningMessageFillinRecordViewModel
    {
        public string FillinDateTime { get; set; } //填報時間
        public string MyName { get; set; } //填報人員
        public string FillinState { get; set; } //事件處理狀況
        public string Memo { get; set; } //備註
    }
    public class FillinInfo
    {
        public string WMSN { get; set; } //警示訊息編號
        public string FillinState { get; set; } //事件處理狀況
        public string Memo { get; set; } //備註
    }
    public class WarningMessageCreateModel : ICreateWarningMessage
    {
        //public string WMType { get; set; } //事件等級
        [JsonConverter(typeof(StringEnumConverter))]
        public WMClass WMClass { get; set; } //事件類別
        public string FSN { get; set; } //發生地點
        //public string Message { get; set; } //事件內容
        public string UserName { get; set; } //警報來源
        public decimal? Location_X { get; set; }
        public decimal? Location_Y { get; set; }
    }

    public interface ICreateWarningMessage
    {
        WMClass WMClass { get; set; } //事件類別
        string FSN { get; set; } //發生地點
        string UserName { get; set; } //警報來源
        decimal? Location_X { get; set; }
        decimal? Location_Y { get; set; }
    }
}

MinSheng_MIS/Controllers/API/WarningMessage_ManagementController.cs
using MinSheng_MIS.Models;
using MinSheng_MIS.Models.ViewModels;
using MinSheng_MIS.Services;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using static MinSheng_MIS.Models.ViewModels.InspectionPlan_ManagementViewModel;
using System.Threading.Tasks;

namespace MinSheng_MIS.Controllers.API
{
    public class WarningMessage_ManagementController : ApiController
    {
        public class AddWarningMessageController : ApiController
        {
            private readonly Bimfm_MinSheng_MISEntities _db;
            private readonly WarningMessageService _warningMessageService;

            public AddWarningMessageController()
            {
                _db = new Bimfm_MinSheng_MISEntities();
                _warningMessageService = new WarningMessageService(_db);
            }
            public async Task<JsonResService<string>> Post(WarningMessageCreateModel info)
            {
                JsonResService<string> result = new JsonResService<string>();
                try
                {
                    string userID = HttpContext.Current.User.Identity.Name;
                    if (string.IsNullOrEmpty(userID))
                    {
                        result.AccessState = ResState.Failed;
                        result.ErrorMessage = "無登入者資料";
                    }
                    else
                    {
                        info.UserName = userID;
                        await _warningMessageService.AddOrUpdateWarningMessageAsync(info);
                        result.AccessState = ResState.Success;
                    }
                }
                catch (Exception ex)
                {
                    result.AccessState = ResState.Failed;
                    result.ErrorMessage = ex.Message;
                }
                return result;
            }
        }
    }
}

MinSheng_MIS/Controllers/WarningMessage_ManagementController.cs
using Microsoft.AspNet.Identity;
using MinSheng_MIS.Models;
using MinSheng_MIS.Models.ViewModels;
using MinSheng_MIS.Services;
using MinSheng_MIS.Services.Helpers;
using MinSheng_MIS.Surfaces;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace MinSheng_MIS.Controllers
{
    public class WarningMessage_ManagementController : Controller
    {
        private readonly Bimfm_MinSheng_MISEntities _db;
        private readonly WarningMessageService _warningMessageService;

        public WarningMessage_ManagementController()
        {
            _db = new Bimfm_MinSheng_MISEntities();
            _warningMessageService = new WarningMessageService(_db);
        }
        #region 警示訊息管理
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> AddWarningMessagenAsync(WarningMessageCreateModel info)
        {
            try
            {
                await _warningMessageService.AddOrUpdateWarningMessageAsync(info);
                return Content(JsonConvert.SerializeObject(new JObject { { "Succeed", true } }), "application/json");
            }
            catch(Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion

        #region 警示訊息填報
        public ActionResult Edit(string id)
        {
            ViewBag.id = id;
            return View();
        }
        [HttpPost]
        public ActionResult WarningMessageFillin(FillinInfo info)
        {
            try
            {
                _warningMessageService.AddWarningMessageFillinRecord(info, User.Identity.Name);
                return Content(JsonConvert.SerializeObject(new JObject { { "Succeed", true } }), "application/json");
            }
            catch(Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            } 
        }
        #endregion

        #region 警示訊息詳情
        public ActionResult Detail(string id)
        {
            ViewBag.id = id;
            return View();
        }
        [HttpGet]
        public ActionResult GetWarningMessageInfo(string WMSN)
        {
            try
            {
                var messageinfo = _db.WarningMessage.Find(WMSN);
                var WMTypedic = Surface.WMType(); //警示訊息事件等級對照
                var WMState = Surface.WMState(); //警示訊息事件處理狀況對照
                var FloorName = _db.Floor_Info.Find(messageinfo.FSN)?.FloorName.ToString();
                var Area = _db.Floor_Info.Find(messageinfo.FSN)?.AreaInfo?.Area.ToString();

                //取得警示訊息資訊
                WarningMessageViewModel warningMessage = new WarningMessageViewModel();
                warningMessage.WMSN = WMSN;
                warningMessage.WMType = WMTypedic[messageinfo.WMType];
                warningMessage.WMState = WMState[messageinfo.WMState];
                warningMessage.TimeOfOccurrence = messageinfo.TimeOfOccurrence.ToString("yyyy-MM-dd HH:mm:ss");
                warningMessage.Location = Area + " " + FloorName;
                warningMessage.Message = messageinfo.Message;

                //取得填報紀錄
                var records = _db.WarningMessageFillinRecord.Where(x => x.WMSN == WMSN).ToList();
                if (records.Count() > 0)
                {
                    List<WarningMessageFillinRecordViewModel> rlist = new List<WarningMessageFillinRecordViewModel>();
                    foreach (var record in records)
                    {
                        WarningMessageFillinRecordViewModel r = new WarningMessageFillinRecordViewModel();
                        r.FillinDateTime = record.FillinDateTime.ToString("yyyy-MM-dd HH:mm:ss");
                        r.MyName = _db.AspNetUsers.Where(x => x.UserName == record.FillinUserName).FirstOrDefault().MyName.ToString();
                        r.FillinState = WMState[record.FillinState];
                        r.Memo = record.Memo;
                        rlist.Add(r);
                    }
                    warningMessage.WarningMessageFillinRecord = rlist;
                }
                else
                {
                    warningMessage.WarningMessageFillinRecord = null;
                }

                string result = JsonConvert.SerializeObject(warningMessage);
                return Content(result, "application/json");
            }
            catch(Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion

        #region 小鈴鐺警示訊息
        [AllowAnonymous]
        [HttpGet]
        public ActionResult BellMessageInfo()
        {
            try
            {
                JArray messages = new JArray();
                var messagelist = _db.WarningMessage.Where(x => x.WMState == "1" || x.WMState == "2").OrderByDescending(x => x.TimeOfOccurrence).ToList();
                foreach (var m in messagelist)
                {
                    JObject message = new JObject();
                    Floor_Info floor = _db.Floor_Info.Find(m.FSN);

                    message.Add("WMSN", m.WMSN);
                    if (floor != null)
                    {
                        message.Add("Location", floor.AreaInfo.Area + floor.FloorName);
                    }
                    message.Add("Message", m.Message);
                    message.Add("WMType", m.WMType);
                    message.Add("WMState", m.WMState);
                    message.Add("TimeOfOccurrence", m.TimeOfOccurrence.ToString("yyyy-MM-dd HH:mm:ss"));
                    messages.Add(message);
                }

                return Content(JsonConvert.SerializeObject(messages), "application/json");
            }
            catch (Exception ex)
            {
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(string.Join(",", ex.Message));
            }
        }
        #endregion

        #region 小鈴鐺已讀列表 - 讀取
        [HttpGet]
        public ActionResult GetHaveReadMessage()
        {
            JsonResService<JArray> res = new JsonResService<JArray>();
            try
            {
                string folderPath = Server.MapPath("~/Files/HaveReadMessage");
                if (!Directory.Exists(folderPath))
                {
                    Directory.CreateDirectory(folderPath);
                }

                string fileName = Server.MapPath($"~/Files/HaveReadMessage/{User.Identity.GetUserId()}.json");
                if (!System.IO.File.Exists(fileName))
                {
                    System.IO.File.WriteAllText(fileName, "[]");
                }

                string jsonContent = System.IO.File.ReadAllText(fileName);
                res.AccessState = ResState.Success;
                res.Datas = JsonConvert.DeserializeObject<JArray>(jsonContent);
                return Content(JsonConvert.SerializeObject(res), "application/json");
            }
            catch (Exception ex)
            {
                res.AccessState = ResState.Failed;
                res.ErrorMessage = ex.Message;
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(JsonConvert.SerializeObject(res), "application/json");
            }
        }
        #endregion

        #region 小鈴鐺已讀列表 - 增加
        [HttpPost]
        public ActionResult PostHaveReadMessage(List<string> WMSNs)
        {
            JsonResService<JArray> res = new JsonResService<JArray>();
            try
            {
                string folderPath = Server.MapPath("~/Files/HaveReadMessage");
                if (!Directory.Exists(folderPath))
                {
                    Directory.CreateDirectory(folderPath);
                }

                string fileName = Server.MapPath($"~/Files/HaveReadMessage/{User.Identity.GetUserId()}.json");
                if (!System.IO.File.Exists(fileName))
                {
                    System.IO.File.WriteAllText(fileName, "[]");
                }

                string jsonContent = System.IO.File.ReadAllText(fileName);
                JArray data = (JArray)JsonConvert.DeserializeObject(jsonContent);
                HashSet<string> set = new HashSet<string>();

                foreach (string WMSN in data)
                {
                    set.Add(WMSN);
                }

                foreach (string WMSN in WMSNs)
                {
                    set.Add(WMSN);
                }

                JArray jsonArray = new JArray(set.Select(item => new JValue(item)));

                System.IO.File.WriteAllText(fileName, JsonConvert.SerializeObject(jsonArray));
                res.AccessState = ResState.Success;
                return Content(JsonConvert.SerializeObject(res), "application/json");
            }
            catch (Exception ex)
            {
                res.AccessState = ResState.Failed;
                res.ErrorMessage = ex.Message;
                LogHelper.WriteErrorLog(this, User.Identity.Name, ex.Message.ToString());
                return Content(JsonConvert.SerializeObject(res), "application/json");
            }
        }
        #endregion
    }
}

MinSheng_MIS/Views/WarningMessage_Management/Detail.cshtml
@{
    ViewBag.Title = "警示訊息詳情";
}

@section styles {
    @Html.Partial("DataGridScripts")

    <style>
        .datatable-easyui .datagrid-wrap {
            height: 400px !important;
        }

        no-data {
            padding: 1rem;
            display: block;
            text-align: center;
        }
    </style>
}

<h2>@ViewBag.Title</h2>
<section>
    <div class="info-area">
        <div class="datatable datatable-small">
            <div class="datatable-body">
                <table class="datatable-table" id="ItemInfo"></table>
            </div>
        </div>
    </div>

        <div class="datatable mt-5">
            <div class="datatable-header">填報記錄</div>
            <div class="datatable-body datatable-easyui">
                <table id="DataGrid"></table>
            </div>
        </div>
</section>

    @section scripts {
        <script>

        const WMSN = '@ViewBag.id';
        const apiUrl = '@Url.Action("GetWarningMessageInfo", "WarningMessage_Management")' + `/?WMSN=${WMSN}`;

        const SerializedName = [
            { text: "事件等級", value: "WMType" },
            { text: "事件處理狀況", value: "WMState" },
            { text: "發生時間", value: "TimeOfOccurrence", type: "Date" },
            { text: "發生地點", value: "Location" },
            { text: "事件內容", value: "Message" },

        ]

        const fakeData = {
            WMSN: "230101001",
            PMSN: "1",
            WMType: "一般",
            WMState: "已處理",
            TimeOfOccurrence: "2023-01-01T06:30:27",
            Location: "進流抽水站 B2F",
            Message: "巡檢路徑偏移",
            WarningMessageFillinRecord: generateRandomData()
        }

        window.onload = function () {
            readData(apiUrl);
        }

        function readData(url = null) {

            url == null ? onSuccess(fakeData) :
                $.ajax({
                    url: url,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: onSuccess,
                    error: onError
                })

            function onSuccess(res) {
                console.log(res);
                $("#ItemInfo").append(createTableInner(res, SerializedName));
                if (res?.WarningMessageFillinRecord && res?.WarningMessageFillinRecord.length != 0) {
                    initDatagrid(res.WarningMessageFillinRecord);
                }
                else {
                    $('#DataGrid').before("<no-data>無填報資料</no-data>")
                }
            }
            function onError(res) {
                console.log(res);
            }
        }

        function initDatagrid(data) {
            data.forEach((el, i) => {
                data[i].FillinDateTime = dateTransform(el.FillinDateTime);
            })
            $('#DataGrid').datagrid({
                data,
                fit: true,
                method: 'GET',
                remoteSort: false,
                sortOrder: 'asc',
                singleSelect: true,
                selectOnCheck: true,
                checkOnSelect: false,
                columns: [[
                    { field: 'FillinDateTime', title: '填報時間', align: 'center', width: 250, sortable: true },
                    { field: 'MyName', title: '填報人員', align: 'center', width: 250, sortable: true },
                    { field: 'FillinState', title: '事件處理狀況', align: 'center', width: 250, sortable: true },
                    { field: 'Memo', title: '備註', align: 'center', width: 900, sortable: true },
                ]]
            });

            const observer = new ResizeObserver((e) => {
                $('#DataGrid').datagrid("resize")
            });
            observer.observe(document.querySelector(".datatable-easyui"));

        }

        function generateRandomData() {
            const randomData = [];
            for (let i = 0; i < 20; i++) {
                randomData.push({
                    FillinDateTime: new Date().toLocaleString(),
                    FillinUserName: "User " + (i + 1),
                    FillinState: Math.random() > 0.5 ? "已處理" : "未處理",
                    Memo: "Random Memo Random Memo" + (i + 1)
                });
            }
            return randomData;
        }
        </script>
    }

MinSheng_MIS/Views/WarningMessage_Management/Edit.cshtml
@{
    ViewBag.Title = "警示訊息填報";
}
@section styles {
    @Html.Partial("DataGridScripts")
    <style>
        .edit-area .form label.btn {
            margin-top: 0;
        }

        .edit-area .form label.btn:hover {
            color: #fff;
        }

        @@media (min-width: 992px) {
            .edit-area .form {
                align-items: flex-start;
            }
        }
    </style>
}

<h2>警示訊息填報</h2>

<section>
    <div class="info-area">
        <div class="datatable datatable-small">
            <div class="datatable-body">
                <table class="datatable-table" id="ItemInfo"></table>
            </div>
        </div>

        <div class="edit-area info-zone">
            <form class="form p-0 bg-transparent">
                <div class="form-group w-100 required">
                    <label for="">處理狀態</label>
                    <div class="d-flex flex-sm-row" style="gap:0.5em;">
                        <label class="btn" for="FillinState_1">
                            <input type="radio" class="form-check-input" id="FillinState_1" name="FillinState" value="2"
                                   required>
                            處理中
                        </label>
                        <label class="btn" for="FillinState_2">
                            <input type="radio" class="form-check-input" id="FillinState_2" name="FillinState" value="3"
                                   required>
                            已處理
                        </label>
                    </div>
                </div>
                <input type="text" class="form-check-input" id="WMSN" name="WMSN" value='@ViewBag.id' required hidden>
                <div class="form-group w-100">
                    <label for="Memo">備註</label>
                    <textarea class="w-100" name="Memo" id="Memo" rows="5"></textarea>
                </div>
                <div id="FileUploader"></div>
            </form>
        </div>
    </div>
</section>

<div class="edit-button-area">
    <button class="btn btn-back" id="back">返回</button>
    <button class="btn btn-submit" id="submit">儲存</button>
</div>

@section scripts {
    <script>
const WMSN = '@ViewBag.id';
const apiUrl = '@Url.Action("GetWarningMessageInfo", "WarningMessage_Management")' + `/?WMSN=${WMSN}`;

const SerializedName = [
    { text: "事件等級", value: "WMType" },
    { text: "事件處理狀況", value: "WMState" },
    { text: "發生時間", value: "TimeOfOccurrence", type: "Date" },
    { text: "發生地點", value: "Location" },
    { text: "時間內容", value: "Message" },
]

const fakeData = {
    WMSN: "1",
    WMType: "緊急",
    WMState: "待處理",
    TimeOfOccurrence: "2022/02/01 11:20:10",
    Location: "B1儲藏室",
    Message: "電力失常",
}

function readData(url = null) {
    url == null ? onSuccess(fakeData) :
        $.ajax({
            url: url,
            type: "GET",
            dataType: "json",
            contentType: "application/json;charset=utf-8",
            success: onSuccess,
            error: onError
        })

    function onSuccess(res) {
        console.log(res);
        $("#ItemInfo").append(createTableInner(res, SerializedName));
    }
    function onError(res) {
        console.log(res);
    }
}

function save() {
    let isValidity = [...document.forms].map(e => e.reportValidity()).every(e => e);
    console.log("todo save():", isValidity)
    if (!isValidity) return;

    let form = new FormData(document.querySelector(".edit-area .form"))
    console.log(Object.fromEntries(form.entries()))

    $.ajax({
        url: '@Url.Action("WarningMessageFillin", "WarningMessage_Management")',
        data: form,
        type: "POST",
        contentType: false,
        processData: false,
        success: onSuccess,
        error: onError
    })
    function onSuccess(res) {
        console.log(res);
        createDialogModal({
            id: "DialogModal-Success", inner: "儲存成功！",
            onHide: () => { window.location.href = "/WarningMessage_Management/Index"; }
        });
    }
    function onError(res) {
        console.log(res);
        createDialogModal({ id: "DialogModal-Error", inner: `儲存失敗！` + `${res?.responseText || ""}` })
    }
}

function addButtonEvent() {
    $("#back").click(function () {
        history.back();
    });
    $("#submit").click(function () {
        save();
    });
}

window.onload = function () {
    addButtonEvent();
    readData(apiUrl);
}
    </script>
}

MinSheng_MIS/Views/WarningMessage_Management/Read.cshtml
@{
    ViewBag.Title = "警示訊息詳情";
}

@section styles {
    @Html.Partial("DataGridScripts")
    <script src="/Scripts/datatable.js" defer></script>

    <style>
        .datatable-easyui .datagrid-wrap {
            height: 400px !important;
        }

        no-data {
            padding: 1rem;
            display: block;
            text-align: center;
        }
    </style>
}

<h2>@ViewBag.Title</h2>

<div class="datatable datatable-small mt-5">
    <div class="datatable-body">
        <table class="datatable-table" id="ItemInfo"></table>
    </div>
</div>

<div class="datatable mt-5">
    <div class="datatable-header">填報記錄</div>
    <div class="datatable-body datatable-easyui">
        <table id="DataGrid"></table>
    </div>
</div>

@section scripts {
    <script>

        const WMSN = '@ViewBag.id';
        const apiUrl = '@Url.Action("GetWarningMessageInfo", "WarningMessage_Management")' + `/?WMSN=${WMSN}`;

        const SerializedName = [
            { text: "事件等級", value: "WMType" },
            { text: "事件處理狀況", value: "WMState" },
            { text: "發生時間", value: "TimeOfOccurrence" },
            { text: "發生地點", value: "Location" },
            { text: "事件內容", value: "Message" },

        ]

        const fakeData = {
            WMSN: "230101001",
            PMSN: "1",
            WMType: "一般",
            WMState: "已處理",
            TimeOfOccurrence: "2023-01-01T06:30:27",
            Location: "進流抽水站 B2F",
            Message: "巡檢路徑偏移",
            WarningMessageFillinRecord: generateRandomData()
        }

        window.onload = function () {
            readData(apiUrl);
        }

        function readData(url = null) {

            url == null ? onSuccess(fakeData) :
                $.ajax({
                    url: url,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: onSuccess,
                    error: onError
                })

            function onSuccess(res) {
                console.log(res);
                $("#ItemInfo").append(createTableInner(res, SerializedName));
                if (res?.WarningMessageFillinRecord && res?.WarningMessageFillinRecord.length != 0) {
                    initDatagrid(res.WarningMessageFillinRecord);
                }
                else {
                    $('#DataGrid').before("<no-data>無填報資料</no-data>")
                }
            }
            function onError(res) {
                console.log(res);
            }
        }

        function initDatagrid(data) {
            $('#DataGrid').datagrid({
                data,
                fit: true,
                method: 'GET',
                remoteSort: false,
                sortOrder: 'asc',
                singleSelect: true,
                selectOnCheck: true,
                checkOnSelect: false,
                columns: [[
                    { field: 'FillinDateTime', title: '填報時間', align: 'center', width: 220, sortable: true },
                    { field: 'MyName', title: '填報人員', align: 'center', width: 120, sortable: true },
                    { field: 'FillinState', title: '事件處理狀況', align: 'center', width: 150, sortable: true },
                    { field: 'Memo', title: '備註', align: 'center', sortable: true },
                ]]
            });

            const observer = new ResizeObserver((e) => {
                $('#DataGrid').datagrid("resize")
            });
            observer.observe(document.querySelector(".datatable-easyui"));

        }

        function generateRandomData() {
            const randomData = [];
            for (let i = 0; i < 20; i++) {
                randomData.push({
                    FillinDateTime: new Date().toLocaleString(),
                    FillinUserName: "User " + (i + 1),
                    FillinState: Math.random() > 0.5 ? "已處理" : "未處理",
                    Memo: "Random Memo Random Memo" + (i + 1)
                });
            }
            return randomData;
        }
    </script>
}