MinSheng_MIS/Controllers/EquipmentInfo_ManagementController.cs
using MinSheng_MIS.Models;
using MinSheng_MIS.Models.ViewModels;
using MinSheng_MIS.Services;
using MinSheng_MIS.Services.Helpers;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using OfficeOpenXml;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;
using System.Web.Mvc;
using static MinSheng_MIS.Services.UniParams;

namespace MinSheng_MIS.Controllers
{
    public class EquipmentInfo_ManagementController : Controller
    {
        
        private readonly Bimfm_MinSheng_MISEntities _db;
        private readonly EquipmentInfo_ManagementService _eMgmtService;
        private readonly OneDeviceOneCard_ManagementService _dCardService;

        public EquipmentInfo_ManagementController()
        {
            _db = new Bimfm_MinSheng_MISEntities();
            _eMgmtService = new EquipmentInfo_ManagementService(_db);
            _dCardService = new OneDeviceOneCard_ManagementService(_db);
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            _eMgmtService.SetServer(Server);  // 將 Server 傳遞給服務層
            _dCardService.SetServer(Server);  // 將 Server 傳遞給服務層
        }

        #region 資產管理
        public ActionResult Index()
        {
            return View();
        }
        #endregion

        #region 新增 設備
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// 新增設備API
        /// </summary>
        /// <param name="data">Input</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> CreateEquipment(EquipmentInfoCreateViewModel data)
        {
            try
            {
                // Data Annotation
                if (!ModelState.IsValid) return Helper.HandleInvalidModelState(this, applyFormat:true);  // Data Annotation未通過

                // 建立 EquipmentInfo
                data.SetEsn(await _eMgmtService.CreateEquipmentInfoAsync(data));

                // 建立 RFID
                if (data.RFIDList?.Any() == true)
                {
                    data.SetRFIDListESN();
                    await _eMgmtService.CreateRFIDAsync(data);
                }
                    

                // 建立一機一卡模板資料 (非必填)
                if (data.TSN != null)
                {
                    // 建立 Equipment_AddFieldValue (非必填)
                    if (data.AddFieldList != null && data.AddFieldList.Any())
                        await _eMgmtService.CreateEquipmentAdditionalFieldsValue(data);

                    // 建立 Equipment_MaintainItemValue (非必填)
                    if (data.MaintainItemList != null && data.MaintainItemList.Any())
                        await _eMgmtService.CreateEquipmentMaintainItemsValue(data);
                }

                // 照片上傳
                if (data.EPhoto?.ContentLength > 0)
                    _eMgmtService.UploadPhoto(data.EPhoto, data.ESN);

                await _db.SaveChangesAsync();

                return Content(JsonConvert.SerializeObject(new JsonResService<string>
                {
                    AccessState = ResState.Success,
                    ErrorMessage = null,
                    Datas = null,
                }), "application/json");
            }
            catch (MyCusResException ex)
            {
                return Helper.HandleMyCusResException(this, ex);
            }
            catch (Exception)
            {
                return Helper.HandleException(this);
            }
        }
        #endregion

        #region 編輯 設備
        public ActionResult Edit(string id)
        {
            ViewBag.id = id;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> EditEquipment(EquipmentInfoEditViewModel data)
        {
            try
            {
                // Data Annotation
                if (!ModelState.IsValid) return Helper.HandleInvalidModelState(this, applyFormat: true);  // Data Annotation未通過

                var equipment = await _db.EquipmentInfo.SingleOrDefaultAsync(x => x.ESN == data.ESN)
                    ?? throw new MyCusResException("設備不存在！");

                using (var trans = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                {
                    // 是否變更一機一卡模板
                    bool changeTemplate = data.TSN != equipment.TSN;

                    // 更新設備資訊
                    await _eMgmtService.UpdateEquipmentInfoAsync(data);

                    // 更新RFID
                    data.SetRFIDListESN();
                    await _eMgmtService.UpdateRFIDAsync(data);

                    // 更新一機一卡模板資料
                    if (changeTemplate)
                    {
                        // Equipment_AddFieldValue : 全部刪除
                        _eMgmtService.DeleteAddFieldValueList(equipment.Equipment_AddFieldValue);

                        // Equipment_MaintainItemValue : 全部刪除
                        // 刪除關聯的待派工 Equipment_MaintenanceForm
                        _eMgmtService.DeleteMaintainItemValueList(equipment.Equipment_MaintainItemValue);
                    }

                    if (data.TSN != null && changeTemplate)
                    {
                        // 建立 Equipment_AddFieldValue (非必填)
                        if (data.AddFieldList?.Any() == true)
                            await _eMgmtService.CreateEquipmentAdditionalFieldsValue(data);

                        // 建立 Equipment_MaintainItemValue (非必填)
                        if (data.MaintainItemList?.Any() == true)
                            await _eMgmtService.CreateEquipmentMaintainItemsValue(data);
                    }
                    else if (data.TSN != null)
                    {
                        // 更新 Equipment_AddFieldValue (非必填)
                        if (data.AddFieldList?.Any() == true)
                            await _eMgmtService.UpdateEquipmentAdditionalFieldsValueAsync(data);

                        // 更新 Equipment_MaintainItemValue (非必填)
                        if (data.MaintainItemList?.Any() == true)
                            await _eMgmtService.UpdateEquipmentMaintainItemsValue(data);
                    }

                    // 照片刪除
                    if (string.IsNullOrEmpty(data.FileName))
                        _eMgmtService.DeletePhoto(data.ESN);

                    // 照片上傳
                    if (data.EPhoto?.ContentLength > 0)
                        _eMgmtService.UploadPhoto(data.EPhoto, data.ESN);

                    await _db.SaveChangesAsync();

                    trans.Complete();
                }

                return Content(JsonConvert.SerializeObject(new JsonResService<string>
                {
                    AccessState = ResState.Success,
                    ErrorMessage = null,
                    Datas = null,
                }), "application/json");
            }
            catch (MyCusResException ex)
            {
                return Helper.HandleMyCusResException(this, ex);
            }
            catch (Exception)
            {
                return Helper.HandleException(this);
            }
        }
        #endregion

        #region 設備 詳情
        public ActionResult Detail(string id)
        {
            ViewBag.id = id;
            return View();
        }

        public async Task<ActionResult> ReadBody(string id)
        {
            try
            {
                // 獲取設備詳情
                var equipment = await _eMgmtService.GetEquipmentInfoAsync<EquipmentInfoDetailViewModel>(id);
                // 獲取增設基本資料欄位
                equipment.AddFieldList = _eMgmtService.GetAddFieldList(id);
                // 獲取保養項目
                equipment.MaintainItemList = _eMgmtService.GetMaintainItemList(id);
                // 獲取RFID
                equipment.RFIDList = await _eMgmtService.GetRFIDListAsync(id);

                if (!string.IsNullOrEmpty(equipment.TSN))
                {
                    // 獲取檢查項目
                    equipment.CheckItemList = await _dCardService.GetCheckItemDetailListAsync(equipment.TSN);
                    // 獲取填報項目名稱/單位
                    equipment.ReportItemList = await _dCardService.GetReportItemDetailListAsync(equipment.TSN);
                }

                return Content(JsonConvert.SerializeObject(new JsonResService<EquipmentInfoDetailViewModel>
                {
                    AccessState = ResState.Success,
                    ErrorMessage = null,
                    Datas = equipment,
                }), "application/json");
            }
            catch (MyCusResException ex)
            {
                return Helper.HandleMyCusResException(this, ex);
            }
            catch (Exception)
            {
                return Helper.HandleException(this);
            }
        }
        #endregion

        #region 停用 設備
        public ActionResult Delete()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> DisableEquipment(string id)
        {
            try
            {
                var equipment = await _db.EquipmentInfo.SingleOrDefaultAsync(x => x.ESN == id)
                        ?? throw new MyCusResException("設備不存在！");
                if (IsEnumEqualToStr(equipment.EState, EState.Repair))
                    throw new MyCusResException("設備報修中，不可停用！");
                if (IsEnumEqualToStr(equipment.EState, EState.Disable))
                    throw new MyCusResException("設備已停用！");

                using (var trans = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                {
                    // EquipmentInfo : 停用設備資料, 停用模板
                    _eMgmtService.DisableEquipment(equipment);
                    // 刪除關聯的待派工 EquipmentReportForm
                    equipment.EquipmentReportForm

MinSheng_MIS/Views/EquipmentInfo_Management/Delete.cshtml
@{
    ViewBag.Title = "設備 刪除";
}
@section styles {
    @Html.Partial("DataGridScripts")
    <script src="/Scripts/dataTable/RepairRecord.js" defer></script>
    <script src="/Scripts/ImageDisplay.js" defer></script>
}

<h2>@ViewBag.Title</h2>

<section>
    <div class="info-area edit-area-md">
        <div class="d-flex flex-column gap-2 w-100">
            <div class="zone-title">基本資訊</div>
            <div class="datatable">
                <div class="datatable-body">
                    <table class="datatable-table" id="OriginalInfo"></table>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column w-100">
            <div class="group-sb-title">
                <i class="fa-solid fa-map-pin"></i>
                <div>RFID</div>
            </div>
            <section id="EquipmentRFID"></section>
        </div>
        <hr class="hr-default" style="display: none;">
        <div class="flex-column gap-2 w-100" style="display: none;" id="SampleZone">
            <div class="zone-title">一機一卡模板資訊</div>
            <div class="datatable">
                <div class="datatable-body">
                    <table class="datatable-table" id="SampleInfo"></table>
                </div>
            </div>
            <div class="flex-column w-100" id="addFieldSection">
                <div class="group-sb-title">
                    <i class="fa-solid fa-map-pin"></i>
                    <div>增設基本資料欄位</div>
                </div>
                <div class="datatable">
                    <div class="datatable-body">
                        <table class="datatable-table" id="AddField"></table>
                    </div>
                </div>
            </div>
            <div class="flex-column w-100" id="maintainSection">
                <div class="group-sb-title">
                    <i class="fa-solid fa-map-pin"></i>
                    <div>保養資訊</div>
                </div>
                <div class="datatable">
                    <div class="datatable-body">
                        <table class="datatable-table" id="MaintainInfo"></table>
                    </div>
                </div>
            </div>
            <div class="flex-column w-100" id="inspectionInfoSection">
                <div class="group-sb-title">
                    <i class="fa-solid fa-map-pin"></i>
                    <div>巡檢資訊</div>
                </div>
                <div class="datatable">
                    <div class="datatable-body">
                        <table class="datatable-table" id="InspectionInfo"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="edit-button-area">
    <button class="btn btn-back" id="back">返回</button>
    <button class="btn btn-delete" id="delete">刪除</button>
</div>
            



@section scripts {
    <script>
        const ESN = '@ViewBag.id';
        //let apiUrl = '@Url.Action("ReadBody", "RepairRecord_Management")' + `/${ESN}`;
        let apiUrl = null;
        let allData = {};
        $(async function () {
            addButtonEvent();
            readData(apiUrl);
        })

        //基本資料欄位
        const SerializedName = [
            { text: "設備圖片", value: "EPhoto", type: "ImgPath" },
            { text: "設備名稱", value: "EName" },
            { text: "設備編號", value: "NO" },
            { text: "棟別", value: "AFN" },
            { text: "樓層", value: "FSN" },
            { text: "設備廠牌", value: "Brand" },
            { text: "設備型號", value: "Model" },
            { text: "設備廠商", value: "Vendor" },
            { text: "聯絡電話", value: "ContactPhone" },
            { text: "安裝日期", value: "InstallDate" },
            { text: "使用電壓", value: "OperatingVoltage" },
            { text: "其他耗材資料", value: "OtherInfo" },
            { text: "備註", value: "Memo" },
        ]

        const SampleName = [
            { text: "模板名稱", value: "SampleName" },
        ]

        const fakeData = {
            Datas: {
                ESN: "000123",
                EPhoto: "/Files/EquipmentInfo/E24122400001.png",
                EName: "名稱名稱",
                NO: "365541",
                AFN: "進流抽水站",
                FSN: "B1F",
                Brand: "廠牌名稱",
                Model: "op1002",
                Vendor: "郝繽紛公司",
                ContactPhone: "0909111222",
                InstallDate: "2024/08/10",
                OperatingVoltage: "20V",
                OtherInfo: "資料資料",
                Memo: "這是一段備註",
                RFID: [
                    {
                        Name: "軸承潤滑劑一",
                        RFIDInternalCode: "A101",
                        RFIDExternalCode: "125533FFFF",
                        ASN: "A棟",
                        FSN: "5F",
                        Location_X: "",
                        Location_Y: "",
                        Memo: "備註備註",
                    },
                    {
                        Name: "軸承潤滑劑二",
                        RFIDInternalCode: "A102",
                        RFIDExternalCode: "225533FFFF",
                        ASN: "A棟",
                        FSN: "5F",
                        Location_X: "",
                        Location_Y: "",
                        Memo: "備註備註",
                    },
                    {
                        Name: "軸承潤滑劑三",
                        RFIDInternalCode: "A103",
                        RFIDExternalCode: "325533FFFF",
                        ASN: "A棟",
                        FSN: "5F",
                        Location_X: "",
                        Location_Y: "",
                        Memo: "備註備註",
                    },
                ],
                SampleName: "攪拌機模板",
                AddFieldList: [
                    {
                        AFSN: "F0001",
                        Text: "馬力數",
                        Value: "馬力數內容內容"
                    },
                    {
                        AFSN: "F0002",
                        Text: "起動方式",
                        Value: "起動方式內容內容"
                    },
                    {
                        AFSN: "F0003",
                        Text: "額定電流",
                        Value: "額定電流內容內容"
                    },
                    {
                        AFSN: "F0004",
                        Text: "油料編號",
                        Value: "油料編號內容內容"
                    },
                ],
                MaintainItemList: [
                    {
                        MISSN: "I0001",
                        Value: "外部清潔與保養",
                        Period: "每月",
                        NextMaintainDate: "2024/12/25"
                    },
                    {
                        MISSN: "I0002",
                        Value: "各部螺絲鎖定",
                        Period: "每週",
                        NextMaintainDate: "2024/12/25"
                    },
                    {
                        MISSN: "I0003",
                        Value: "檢查管路是否通暢",
                        Period: "每日",
                        NextMaintainDate: "2024/12/25"
                    },
                    {
                        MISSN: "I0004",
                        Value: "軸承潤滑油添加",
                        Period: "每月",
                        NextMaintainDate: "2024/12/25"
                    },
                ],
                Frequency: "1小時",
                CheckItemList: [
                    {
                        CISN: "000123",
                        Value: "馬達是否正常運轉"
                    },
                    {
                        CISN: "000124",
                        Value: "管線是否正常無漏液"
                    },
                    {
                        CISN: "000125",
                        Value: "出口端是否正常出藥"
                    },
                    {
                        CISN: "000126",
                        Value: "設備是否正常無漏水"
                    },
                ],
                ReportItemList: [
                    {
                        RISN: "I0001",
                        Value: "馬達電壓",
                        Unit: "v"
                    },
                    {
                        RISN: "I0002",
                        Value: "電流",
                        Unit: "A"
                    },
                    {
                        RISN: "I0003",
                        Value: "水壓",
                        Unit: "Pa"
                    },
                    {
                        RISN: "I0004",
                        Value: "流量",
                        Unit: "CMH"
                    },
                ]
            },
            ErrorMessage: "",
            State: ""
        }

        //處理傳進來的AddFieldList格式
        function preprocessAddItemsData(array) {
            return array.map((item) => ({
                text: item.Text,
                value: item.Value,
                type: "Variable"
            }))
        }

        function readData(url = null) {

            url == null ? onSuccess(fakeData) :
                $.ajax({
                    url: url,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: onSuccess,
                    error: onError
                })

            function onSuccess(res) {
                console.log(res);
                const data = res.Datas
                const AddItemsData = preprocessAddItemsData(data.AddFieldList);

                $("#OriginalInfo").append(createTableInner(data, SerializedName));
                ImageDisplay(".datatable-img-item>img");
                EquipmentRFID("#EquipmentRFID", data);

                //判斷是否有模板
                if (data.SampleName) {
                    document.querySelector(".hr-default").style.display = "block";
                    document.getElementById("SampleZone").style.display = "flex";

                    if (data.AddFieldList && data.AddFieldList.length > 0) {
                        document.getElementById("addFieldSection").style.display = "flex";
                    } else {
                        document.getElementById("addFieldSection").style.display = "none";
                    }

                    if (data.MaintainItemList && data.MaintainItemList.length > 0) {
                        document.getElementById("maintainSection").style.display = "flex";
                    } else {
                        document.getElementById("maintainSection").style.display = "none";
                    }

                    if (data.Frequency) {
                        document.getElementById("inspectionInfoSection").style.display = "flex";
                    } else {
                        document.getElementById("inspectionInfoSection").style.display = "none";
                    }

                    $("#SampleInfo").append(createTableInner(data, SampleName));
                    $("#AddField").append(createTableInner(data, AddItemsData));
                    MaintainInfo("#MaintainInfo", data);
                    InspectionInfo("#InspectionInfo", data);
                }


            }
            function onError(res) {
                console.log(res);
            }
        }

        function addButtonEvent() {
            $("#back").click(function () {
                history.back();
            });
            $("#delete").click(function () {
                createDeleteDialog({
                    //url: '@Url.Action("DeleteSampleSchedule", "SampleSchedule_Management")' + `?id=${ESN}`,
                    data: ESN,
                    onSuccess() {
                        let url = '@Url.Action("Index", "EquipmentInfo_Management")';
                        window.location.href = url;
                    }
                })
            });
        }


    </script>
}

MinSheng_MIS/Views/EquipmentInfo_Management/Disable.cshtml
@{
    ViewBag.Title = "Disable";
}

<h2>Disable</h2>

MinSheng_MIS/Views/EquipmentInfo_Management/Read.cshtml
@{
    ViewBag.Title = "設備詳情";
}
@section styles {
    <link rel="stylesheet" href="/Content/samplepath.css">
    <!-- Autodesk Forge -->
    <link rel="stylesheet" href="https://developer.api.autodesk.com/modelderivative/v2/viewers/style.min.css?v=v7.60"
        type="text/css">
    <link rel="stylesheet" href="/Content/loading.css" type="text/css">
    <script language="JavaScript"
        src="https://developer.api.autodesk.com/modelderivative/v2/viewers/viewer3D.min.js?v=v7.60" defer></script>
    <script src="/Scripts/Forge/Viewer.Loading.js" defer></script>
    <script src="/Scripts/Forge/Viewer.Toolkit.js" defer></script>
    <script language="JavaScript" src="/Scripts/Forge/UpViewer.js" defer></script>

    <!-- PIXI Draw -->
    <script src="https://pixijs.download/v7.2.2/pixi.js" defer></script>
    <script src="/Scripts/ForgeDraw.js" defer></script>

    <script src="/Scripts/datatable.js" defer></script>
    <script src="/Scripts/tool.js" defer></script>
}

<h2>@ViewBag.Title</h2>
<div class="datatable datatable-small mt-5" style="--datatable-table-th-width: 150px;">
    <div class="datatable-body">
        <table class="datatable-table"></table>
    </div>
</div>

@section scripts {
    <script>
        const ESN = '@ViewBag.id';
        let apiUrl = '@Url.Action("ReadBody", "EquipmentInfo_Management")' + `/${ESN}`;
        //let apiUrl = null;

        const fakeData = {
            ASN: 1,
            Area: "進流抽水站",
            FSN: "1_1",
            Floor: "B1F",
            RoomName: "A",
            System: "BT",
            SubSystem: "BT-11",
            PropertyCode: "A",
            EName: "Test",
            Brand: "111",
            Model: "112",
            FilePath: "/000007.gif",
            LocationX: 22,
            LocationY: 40
        }

        const sn = [
            { text: "棟別", value: "Area" },
            { text: "樓層", value: "Floor" },
            { text: "空間名稱", value: "RoomName" },
            { text: "系統別", value: "System" },
            { text: "子系統別", value: "SubSystem" },
            { text: "財產編碼", value: "PropertyCode" },
            { text: "設備名稱", value: "EName" },
            { text: "廠商", value: "Brand" },
            { text: "型號", value: "Model" },
            { text: "設備使用手冊", value: "FilePath" },
            { text: "設備定位(X座標)", value: "LocationX" },
            { text: "設備定位(Y座標)", value: "LocationY" },
            {
                text: "設備定位", value: "HasLocation", formatter: (v) => {
                    return v != null ? `
                    <div class="viewer3Dcontainer">
                        <div id="viewer3d" style="margin:0;"></div>
                        <canvas id="PathCanvas"></canvas>
                        <div id="current-path-areafloor"></div>
                    </div>
                    `: '';
                }
            }
        ]


        $(function () {
            addButtonEvent();
            readData(apiUrl);
        })

        function readData(url = null) {

            url == null ? onSuccess(fakeData) :
                $.ajax({
                    url: url,
                    type: "GET",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: onSuccess,
                    error: onError
                })

            async function onSuccess(res) {
                console.log(res);
                const HasAsnFsn = res.ASN != null && res.FSN != null;
                const HasLocation = res.LocationX != null && res.LocationY != null;
                res.HasLocation = HasLocation;
                $(".datatable-table").append(createTableInner(res, sn))

                if (!HasLocation || !HasAsnFsn) return;

                $.ajax({
                    url: "/InspectionPlan_Management/AddPlanPath",
                    data: JSON.stringify({
                        ASN: res.ASN,
                        FSN: res.FSN,
                        PathTitle: ''
                    }),
                    type: "POST",
                    dataType: "json",
                    contentType: "application/json;charset=utf-8",
                    success: (PathData) => {
                        console.log(PathData);
                        initializeViewer({
                            BIMPath: PathData.PathSample.BIMPath,
                            BeaconPath: null,
                            callback: () => { initDrawView(res) }
                        });
                    },
                    error: (err) => { console.log(err) }
                })

            }
            function onError(res) {
                console.log(res);
            }
            function initDrawView(res) {
                const view = document.querySelector("#PathCanvas");
                ForgeDraw.init(view, viewer, function () {
                    ForgeDraw.setControl(ForgeDraw.Control.READONLY);

                    let forgePos = new THREE.Vector3(res.LocationX, res.LocationY, 0);
                    let pos = viewer.worldToClient(forgePos);
                    let position = new PIXI.Point(pos.x, pos.y);
                    ForgeDraw.readLineData([{ position, forgePos }]);
                    ForgeDraw.setDrawSetting("point.contextMenu.button", []);
                });
            }
        }

        function addButtonEvent() {
            $("#back").click(function () {
                history.back();
            })
        }
    </script>
}